spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:docfitai}
spring.datasource.username=${POSTGRES_USER:docfitai}
spring.datasource.password=${POSTGRES_PASSWORD:changeme}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
